---
abstract: ~
author:
  - 'Luke Saunders <luke.saunders@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.7
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-ResultSet-WithMetaData
no_index:
  directory:
    - inc
    - t
provides:
  DBIx::Class::ResultSet::WithMetaData:
    file: lib/DBIx/Class/ResultSet/WithMetaData.pm
    version: 0.999001
requires:
  DBIx::Class: 0.08
  DBIx::Class::ResultClass::HashRefInflator: 0
  Data::Alias: 0
  MooseX::Method::Signatures: 0.16
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.999001
